CREATE TABLE  IF NOT EXISTS KNVP(
KUNNR VARCHAR(10) NOT NULL,
VKORG VARCHAR(4) NOT NULL,
VTWEG VARCHAR(2) NOT NULL,
SPART VARCHAR(2) NOT NULL,
PARVW VARCHAR(2) NOT NULL,
PARZA VARCHAR(3) NOT NULL
);

CREATE TABLE  IF NOT EXISTS KNVV(
KUNNR VARCHAR(10) NOT NULL,
VKORG VARCHAR(4) NOT NULL,
VTWEG VARCHAR(2) NOT NULL,
SPART VARCHAR(2) NOT NULL
);


CREATE TABLE  IF NOT EXISTS KNVD(
KUNNR VARCHAR(10) NOT NULL,
VKORG VARCHAR(4) NOT NULL,
VTWEG VARCHAR(2) NOT NULL,
SPART VARCHAR(2) NOT NULL,
NA_KSCHL VARCHAR(2) NOT NULL,
SPRAS VARCHAR(3) NOT NULL);

CREATE TABLE  IF NOT EXISTS KNA1(
KUNNR VARCHAR(10) NOT NULL);

CREATE TABLE  IF NOT EXISTS KNB1(
KUNNR VARCHAR(10) NOT NULL,
BUKRS VARCHAR(4) NOT NULL);

CREATE TABLE  IF NOT EXISTS KNB5(
KUNNR VARCHAR(10) NOT NULL,
BUKRS VARCHAR(4) NOT NULL,
MABER VARCHAR(2) NOT NULL);



select * from kna1;






