CREATE TABLE BKPF(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);

CREATE TABLE BSEG(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL,
BUZEI VARCHAR(3) NOT NULL
);

CREATE TABLE BSEC(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL,
BUZEI VARCHAR(3) NOT NULL
);

CREATE TABLE BSET(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL,
BUZEI VARCHAR(3) NOT NULL
);

