-- KNA1
-- KNVV-
-- KNV1
CREATE TABLE KNA1(
KNA1_ID INT AUTO_INCREMENT PRIMARY KEY,
KUNNR VARCHAR(10) NOT NULL
);

CREATE TABLE KNVV(
KNVV_ID INT AUTO_INCREMENT PRIMARY KEY ,
KNA1_ID INT NOT NULL UNIQUE ,
VKORG VARCHAR(4) NOT NULL,
VTWEG VARCHAR(2) NOT NULL,
SPART VARCHAR(4) NOT NULL,
FOREIGN KEY (KNA1_ID) REFERENCES KNA1(KNA1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE KNVP(
KNVP_ID INT AUTO_INCREMENT PRIMARY KEY,
KNVV_ID INT NOT NULL,
PARVW VARCHAR(2) NOT NULL,
PARZA VARCHAR(3) NOT NULL,
FOREIGN KEY (KNVV_ID) REFERENCES KNVV(KNVV_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE KNVD(
KNVD_ID INT AUTO_INCREMENT PRIMARY KEY,
KNVV_ID INT NOT NULL,
NA_KSCHL VARCHAR(4) NOT NULL, -- OUTPUT TYPE
SPRAS VARCHAR(2) NOT NULL,
FOREIGN KEY (KNVV_ID) REFERENCES KNVV(KNVV_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE KNB1(
KNB1_ID INT AUTO_INCREMENT PRIMARY KEY,
KNA1_ID INT NOT NULL,
BUKRS VARCHAR(4) NOT NULL, 
FOREIGN KEY (KNA1_ID) REFERENCES KNA1(KNA1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE KNB5(
KNB5_ID INT AUTO_INCREMENT PRIMARY KEY,
KNB1_ID INT NOT NULL,
MABER VARCHAR(2) NOT NULL, 
FOREIGN KEY (KNB1_ID) REFERENCES KNB1(KNB1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);