CREATE TABLE IF NOT EXISTS LFA1 (
LIFNR VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFM1 (
LIFNR VARCHAR(10) NOT NULL,
EKORG VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFM2 (
LIFNR VARCHAR(10) NOT NULL,
EKORG VARCHAR(4) NOT NULL,
LTSNR VARCHAR(6) NOT NULL,
WERKS VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFBK (
LIFNR VARCHAR(10) NOT NULL,
BANKS VARCHAR(3) NOT NULL,
BANKL VARCHAR(15) NOT NULL,
BANKN VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFB1 (
LIFNR VARCHAR(10) NOT NULL,
BUKRS VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFB5 (
LIFNR VARCHAR(10) NOT NULL,
BUKRS VARCHAR(4) NOT NULL,
MABER VARCHAR(2) NOT NULL
);






