-- LFA1 - Parent 

CREATE TABLE LFA1(
LFA1_ID INT AUTO_INCREMENT PRIMARY KEY,
LIFNR VARCHAR(10) NOT NULL
);

CREATE TABLE LFM1(
LFM1_ID INT AUTO_INCREMENT PRIMARY KEY ,
LFA1_ID INT NOT NULL,
EKORG VARCHAR(4) NOT NULL,
FOREIGN KEY (LFA1_ID) REFERENCES LFA1(LFA1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LFM2(
LFM2_ID INT AUTO_INCREMENT PRIMARY KEY,
LFM1_ID INT NOT NULL,
LTSNR VARCHAR(6) NOT NULL,
WERKS VARCHAR(4) NOT NULL,
FOREIGN KEY (LFM1_ID) REFERENCES LFM1(LFM1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE LFBK(
LFBK_ID  INT AUTO_INCREMENT PRIMARY KEY,
LFA1_ID INT NOT NULL,
BANKS VARCHAR(3) NOT NULL,
BANKL VARCHAR(15) NOT NULL,
BANKN VARCHAR(18) NOT NULL,
FOREIGN KEY (LFA1_ID) REFERENCES LFA1(LFA1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE LFB1(
LFB1_ID INT AUTO_INCREMENT PRIMARY KEY,
LFA1_ID INT NOT NULL,
BUKRS VARCHAR(4) NOT NULL, 
FOREIGN KEY (LFA1_ID) REFERENCES LFA1(LFA1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LFB5(
LFB5_ID INT AUTO_INCREMENT PRIMARY KEY,
LFB1_ID INT NOT NULL,
MABER VARCHAR(2) NOT NULL, 
FOREIGN KEY (LFB1_ID) REFERENCES LFB1(LFB1_ID) ON DELETE CASCADE ON UPDATE CASCADE
);