CREATE TABLE IF NOT EXISTS BUKPF(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS BVOR (
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BVORG VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSIP(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
WAERS VARCHAR(5) NOT NULL,
BLDAT VARCHAR(8) NOT NULL,
WRBTR VARCHAR(13) NOT NULL,
WRBTR1 VARCHAR(13) NOT NULL,
BUZEI INT(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSEG(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSAD(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
KUNNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSID(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
KUNNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSIS(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
HKONT VARCHAR(10) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSAS(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
HKONT VARCHAR(10) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSAK(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);

CREATE TABLE IF NOT EXISTS BSIK(
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL,
BUZEI INT(3) NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL
);


CREATE TABLE IF NOT EXISTS KNC1(
BUKRS VARCHAR(4) NOT NULL,
KUNNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS LFC1(
BUKRS VARCHAR(4) NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS PAYR(
ZBUKR VARCHAR(4) NOT NULL,
HBKID VARCHAR(5) NOT NULL,
HKTID VARCHAR(5) NOT NULL,
ZLSCH VARCHAR(1) NOT NULL,
CHECKT VARCHAR(13) NOT NULL
);



