-- BKPF - Parent 

CREATE TABLE BVOR(
BVOR_ID INT AUTO_INCREMENT PRIMARY KEY,
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR INT(4) NOT NULL
);

CREATE TABLE BKPF(
BKPF_ID INT AUTO_INCREMENT PRIMARY KEY ,
BVOR_ID INT NOT NULL,
FOREIGN KEY (BVOR_ID) REFERENCES BVOR(BVOR_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BSIP(
BSIP_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
WAERS VARCHAR(5) NOT NULL,
BLDAT VARCHAR(8) NOT NULL,
WRBTR VARCHAR(13) NOT NULL,
WRBTR1 VARCHAR(13) NOT NULL,
BUZEI INT(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BSEC(
BSEC_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI VARCHAR(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BSET(
BSET_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI VARCHAR(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BSEG(
BSEG_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI INT(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BSAD(
BSAD_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
KUNNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL, 
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BSAK(
BSID_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
LIFNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL, 
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BSIS(
BSID_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
HKONT VARCHAR(10) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL,
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BSAS(
BSAS_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
HKONT VARCHAR(10) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL,
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BSID(
BSID_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
KUNNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL, 
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE BSIK(
BSAD_ID INT AUTO_INCREMENT PRIMARY KEY,
BSEG_ID INT NOT NULL UNIQUE,
LIFNR VARCHAR(10) NOT NULL,
UMSKS VARCHAR(1) NOT NULL,
UMSKZ VARCHAR(1) NOT NULL,
AUGDT VARCHAR(8) NOT NULL,
AUGBL VARCHAR(10) NOT NULL,
ZUONR VARCHAR(18) NOT NULL, 
FOREIGN KEY (BSEG_ID) REFERENCES BSEG(BSEG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PAYR(
ZBUKR VARCHAR(4) NOT NULL,
HBKID VARCHAR(5) NOT NULL,
HKTID VARCHAR(5) NOT NULL,
ZLSCH VARCHAR(1) NOT NULL,
CHECKT VARCHAR(13) NOT NULL );

CREATE TABLE IF NOT EXISTS LFC1(
BUKRS VARCHAR(4) NOT NULL,
LIFNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS KNC1(
BUKRS VARCHAR(4) NOT NULL,
KUNNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);
