
CREATE TABLE BKPF(
BKPF_ID INT AUTO_INCREMENT PRIMARY KEY,
BUKRS VARCHAR(4) NOT NULL,
BELNR VARCHAR(10) NOT NULL,
GJAHR VARCHAR(4) NOT NULL
);

CREATE TABLE BSEG(
BSEG_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI VARCHAR(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID)

);

CREATE TABLE BSEC(
BSEC_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI VARCHAR(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID)
);

CREATE TABLE BSET(
BSET_ID INT AUTO_INCREMENT PRIMARY KEY,
BKPF_ID INT NOT NULL,
BUZEI VARCHAR(3) NOT NULL,
FOREIGN KEY (BKPF_ID) REFERENCES BKPF(BKPF_ID)
);

